name: Bandit

on:
  push:  # Run on every commit to any branch
  pull_request:
    branches: [ "main" ]

jobs:
  bandit:
    runs-on: ubuntu-latest

    permissions:
      contents: read                # For actions/checkout
      security-events: write        # To upload SARIF results if needed
      actions: read                 # Needed for private repos

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Bandit Security Scan
        uses: shundor/python-bandit-scan@ab1d87dfccc5a0ffab88be3aaac6ffe35c10d6cd
        with:
          exit_zero: true                    # Don't fail the workflow even if issues are found
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          path: .                            # 👈 Scan the entire repository recursively
